### ISSUE TITLE
Crash without any explanation

### ISSUE THREAD

**Issue by fdev31** [mistricky/codesnap.nvim#153]
On one machine sharing the same VIM setup, I'm unable to use CodeSnap, I get the following error (captured using neovide, but happens with nvim too):

```
❯ ERROR [neovide::bridge::session] 
ERROR [neovide::bridge::session] thread '<unnamed>' panicked at src/copy.rs:39:14:
ERROR [neovide::bridge::session] called `Result::unwrap()` on an `Err` value: Unknown { .. } - "Unknown error while interacting with the clipboard: Error satisfying a paste request"
ERROR [neovide::bridge::session] stack backtrace:
ERROR [neovide::bridge::session]    0:     0x7ba7c5e13880 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h6d42cc84fc840290
ERROR [neovide::bridge::session]    1:     0x7ba7c5e3b463 - core::fmt::write::h5af61a909e3ec64d
ERROR [neovide::bridge::session]    2:     0x7ba7c5e0fe43 - std::io::Write::write_fmt::h5a7b54aa6e4a315d
ERROR [neovide::bridge::session]    3:     0x7ba7c5e136d2 - std::sys::backtrace::BacktraceLock::print::h555579e7396c26ac
ERROR [neovide::bridge::session]    4:     0x7ba7c5e1476f - std::panicking::default_hook::{{closure}}::h9128866118196224
ERROR [neovide::bridge::session]    5:     0x7ba7c5e145da - std::panicking::default_hook::h52e9e7314e0255f6
ERROR [neovide::bridge::session]    6:     0x7ba7c5e15112 - std::panicking::rust_panic_with_hook::h541791bcc774ef34
ERROR [neovide::bridge::session]    7:     0x7ba7c5e14eba - std::panicking::begin_panic_handler::{{closure}}::h6479a2f0137c7d19
ERROR [neovide::bridge::session]    8:     0x7ba7c5e13d99 - std::sys::backtrace::__rust_end_short_backtrace::ha04e7c0fc61ded91
ERROR [neovide::bridge::session]    9:     0x7ba7c5e14b4d - rust_begin_unwind
ERROR [neovide::bridge::session]   10:     0x7ba7c5a979e0 - core::panicking::panic_fmt::h5764ee7030b7a73d
ERROR [neovide::bridge::session]   11:     0x7ba7c5a97db6 - core::result::unwrap_failed::h3ff7104a9ace307a
ERROR [neovide::bridge::session]   12:     0x7ba7c5abc04c - std::sys::backtrace::__rust_begin_short_backtrace::h7944eba8e14689a4
ERROR [neovide::bridge::session]   13:     0x7ba7c5ad1aac - core::ops::function::FnOnce::call_once{{vtable.shim}}::h71e48ea6cfa8d344
ERROR [neovide::bridge::session]   14:     0x7ba7c5e17ddb - std::sys::pal::unix::thread::Thread::new::thread_start::hcc5ed016d554f327
ERROR [neovide::bridge::session]   15:     0x7ba7caba47eb - <unknown>
ERROR [neovide::bridge::session]   16:     0x7ba7cac2818c - <unknown>
ERROR [neovide::bridge::session]   17:                0x0 - <unknown>
```

**Comment by messiias** [comment]
I'm facing a similar problem... Recently i installed nvim using snap and CodeSnap doesn't work anymore, everytime i try to use it show the following error: `vim/loader.lua:0: /snap/core22/current/usr/lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.38' not found (required by /home/messias-olimpio/.local/share/nvim/lazy/codesnap.nvim/lua/generator.so)`

**Comment by fdev31** [comment]
This one

> I'm facing a similar problem... Recently i installed nvim using snap and CodeSnap doesn't work anymore, everytime i try to use it show the following error: `vim/loader.lua:0: /snap/core22/current/usr/lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.38' not found (required by /home/messias-olimpio/.local/share/nvim/lazy/codesnap.nvim/lua/generator.so)`

Seems similar but this one is more clear and is probably solved by compiling the generator.so instead of using the pre-built code.

**Comment by messiias** [comment]
I compiled the generator.so and i'm still having the same problem

**Comment by mistricky** [comment]
This issue will be solved after refactor using https://github.com/codesnap-rs/codesnap

**Comment by mistricky** [comment]
@fdev31 Codesnap.nvim v2.0.0-beta.17 has been released. Could you test whether everything works correctly on beta 17? This version introduces some breaking changes, so it's best to completely uninstall your previous Codesnap.nvim installation and follow the [v2 README](https://github.com/mistricky/codesnap.nvim/tree/refactor/v2?tab=readme-ov-file#codesnapnvim)
